services:
  frontend:
    build: 
      context: ./
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file: 
      - ./server/.env